spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/tweats
    username: tweats
    password: tweats
logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /tweats/api/v1
application:
  link: http://localhost:8080/tweats/api/v1
